### ISSUE TITLE
生成ID大量重复

### ISSUE THREAD

**Issue by QiiSyhx** [hyperf-cloud/snowflake#2]
代码如下，使用的默认配置：
`
        $container = ApplicationContext::getContainer();
        $generator = $container->get(IdGeneratorInterface::class);

        $list = [];
        for ($i = 0; $i < 1000; $i++) {
            $list[] = $generator->generate();
        }
`
每个ID都有大量重复数据生成。
部分数据：
76679067188862980,
    76679067188862980,
    76679067188862980,
    76679067188862980,
    76679067188862980,
    76679067188862980,
    76679067188862980,
    76679067188862980,
    76679067188862980,
    76679067188862990,
    76679067188862990,
    76679067188862990,
    76679067188862990,
    76679067188862990,
    76679067188862990,
    76679067188862990,
    76679067188862990,
    76679067188862990,
    76679067188862990,
    76679067188862990,
    76679067188862990,
    76679067188862990,
    76679067188862990,
    76679067188862990,
    76679067188863000,
    76679067188863000,
    76679067188863000,
    76679067188863000,
    76679067188863000,
    76679067188863000,
    76679067188863000,
    76679067188863000,
    76679067188863000,
    76679067188863000,
    76679067188863000,
    76679067188863000,
    76679067188863000,
    76679067188863000,
    76679067188863000,
    76679067188863000,
    76679067188863000,
    76679067188863020,
    76679067188863020,
    76679067188863020,
    76679067188863020,
    76679067188863020,

**Comment by limingxinleo** [comment]
贴一下配置

**Comment by QiiSyhx** [comment]
return [
    'begin_second' => MetaGeneratorInterface::DEFAULT_BEGIN_SECOND,
    RedisMilliSecondMetaGenerator::class => [
        'pool' => 'default',
        'key' => RedisMilliSecondMetaGenerator::DEFAULT_REDIS_KEY,
    ],
    RedisSecondMetaGenerator::class => [
        'pool' => 'default',
        'key' => RedisMilliSecondMetaGenerator::DEFAULT_REDIS_KEY,
    ],
];

**Comment by limingxinleo** [comment]
没有复现，你要不拉一下这个 https://github.com/limingxinleo/hyperf-demo/tree/excel

```
curl http://127.0.0.1:9501/snow/index
```

**Comment by QiiSyhx** [comment]
我用的是docker那个，没改过什么东西。
用了下面的一些组件：
`"php": ">=7.2",
        "ext-swoole": ">=4.4",
        "hyperf/cache": "~1.1.0",
        "hyperf/command": "~1.1.0",
        "hyperf/config": "~1.1.0",
        "hyperf/contract": "~1.1.0",
        "hyperf/database": "~1.1.0",
        "hyperf/db-connection": "~1.1.0",
        "hyperf/devtool": "~1.1.0",
        "hyperf/di": "~1.1.0",
        "hyperf/dispatcher": "~1.1.0",
        "hyperf/event": "~1.1.0",
        "hyperf/exception-handler": "~1.1.0",
        "hyperf/framework": "~1.1.0",
        "hyperf/guzzle": "~1.1.0",
        "hyperf/http-server": "~1.1.0",
        "hyperf/logger": "~1.1.0",
        "hyperf/memory": "~1.1.0",
        "hyperf/paginator": "~1.1.0",
        "hyperf/pool": "~1.1.0",
        "hyperf/process": "~1.1.0",
        "hyperf/redis": "~1.1.0",
        "hyperf/utils": "~1.1.0",
        "hyperf/config-apollo": "~1.1.0",
        "hyperf/constants": "~1.1.0",
        "hyperf/async-queue": "~1.1.0",
        "hyperf/amqp": "~1.1.0",
        "hyperf/model-cache": "~1.1.0",
        "hyperf/elasticsearch": "~1.1.0",
        "hyperf/tracer": "~1.1.0",
        "hyperf/snowflake": "^1.1"`

**Comment by limingxinleo** [comment]
你在 Docker 里拉一下我的代码试试。。。

我按照你的代码，确实无法复现。。。

**Comment by humengcn** [comment]
@limingxinleo 你好，实测确实会有很多 id 重复，和 @QiiSyhx 一样的代码
![截图](https://user-images.githubusercontent.com/9284625/110451637-58d06400-80ff-11eb-9891-d7d2d10a8730.jpg)

**Comment by limingxinleo** [comment]
@humengcn 用curl测试，不要用浏览器

**Comment by humengcn** [comment]
> @humengcn 用curl测试，不要用浏览器

curl 正常了。。请问是什么原因

**Comment by limingxinleo** [comment]
@humengcn 你用来美化json的脚本，肯定是js写的，它对长整形支持不好，所以缺失了精度

**Comment by humengcn** [comment]
> @humengcn 你用来美化json的脚本，肯定是js写的，它对长整形支持不好，所以缺失了精度

忘了这茬了，感谢
